name: Deploy MS Teams Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: List contents of the directory
        run: ls -al

      - name: Install jq
        run: sudo apt-get install jq

      # Create the artifact filename with version number from package.json
      - name: Create versioned artifact filename
        id: artifact_info
        run: |
          VERSION=$(jq -r .version package.json)
          echo "ARTIFACT_NAME=build_artifact_v$VERSION.zip" >> $GITHUB_ENV

      # Create build artifact (assuming the output is in the 'dist/' directory)
      - name: Create build artifact
        run: |
          mkdir -p artifacts
          zip -r artifacts/$ARTIFACT_NAME dist/

      - name: Set up AWS CLI
        uses: aws-actions/setup-cli@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy the built files to S3 (sync from 'dist/' directory)
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://teams-ms --delete

      # Upload the artifact (zipped 'dist/' folder) to S3 for backup or reference
      - name: Upload build artifact to S3
        run: |
          aws s3 cp artifacts/$ARTIFACT_NAME s3://teams-ms/
